version: '2'

services:
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - docker.env

  main_app:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
    container_name: main_app
    restart: on-failure
    env_file:
      - docker.env
    ports:
      - 3000:3000
